name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
      - 'src/**'
      - 'typedoc.json'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Generate TypeDoc documentation
        run: npm run docs:generate

      - name: Create documentation index
        run: |
          cat > docs/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Discord Notify - API Documentation</title>
              <meta name="description" content="Discord API-compliant notification service for Node.js applications. Inspired by Slack Notify but designed for Discord's rich webhook capabilities.">
              <meta name="keywords" content="discord, notify, notifications, webhook, typescript, nodejs, slack-notify">
              <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism-tomorrow.min.css">
              <style>
                  * {
                      margin: 0;
                      padding: 0;
                      box-sizing: border-box;
                  }
                  
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                      line-height: 1.6;
                      color: #333;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      min-height: 100vh;
                  }
                  
                  .container {
                      max-width: 1200px;
                      margin: 0 auto;
                      padding: 20px;
                  }
                  
                  .header {
                      text-align: center;
                      color: white;
                      margin-bottom: 40px;
                  }
                  
                  .header h1 {
                      font-size: 3rem;
                      margin-bottom: 10px;
                      text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
                  }
                  
                  .header p {
                      font-size: 1.2rem;
                      opacity: 0.9;
                      margin-bottom: 20px;
                  }
                  
                  .inspiration {
                      background: rgba(255,255,255,0.1);
                      padding: 15px;
                      border-radius: 10px;
                      margin-bottom: 30px;
                      backdrop-filter: blur(10px);
                  }
                  
                  .cards {
                      display: grid;
                      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
                      gap: 20px;
                      margin-bottom: 40px;
                  }
                  
                  .card {
                      background: white;
                      padding: 30px;
                      border-radius: 15px;
                      box-shadow: 0 10px 30px rgba(0,0,0,0.2);
                      transition: transform 0.3s ease, box-shadow 0.3s ease;
                      text-decoration: none;
                      color: inherit;
                  }
                  
                  .card:hover {
                      transform: translateY(-5px);
                      box-shadow: 0 20px 40px rgba(0,0,0,0.3);
                  }
                  
                  .card h3 {
                      color: #667eea;
                      margin-bottom: 15px;
                      font-size: 1.5rem;
                  }
                  
                  .card p {
                      margin-bottom: 15px;
                      color: #666;
                  }
                  
                  .features {
                      background: white;
                      padding: 40px;
                      border-radius: 15px;
                      box-shadow: 0 10px 30px rgba(0,0,0,0.2);
                      margin-bottom: 40px;
                  }
                  
                  .features h2 {
                      color: #667eea;
                      margin-bottom: 20px;
                      text-align: center;
                  }
                  
                  .feature-grid {
                      display: grid;
                      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                      gap: 20px;
                  }
                  
                  .feature {
                      padding: 20px;
                      background: #f8f9fa;
                      border-radius: 10px;
                      border-left: 4px solid #667eea;
                  }
                  
                  .feature h4 {
                      color: #667eea;
                      margin-bottom: 10px;
                  }
                  
                  .footer {
                      text-align: center;
                      color: white;
                      margin-top: 40px;
                      padding: 20px;
                      background: rgba(255,255,255,0.1);
                      border-radius: 10px;
                      backdrop-filter: blur(10px);
                  }
                  
                  .social-links {
                      display: flex;
                      justify-content: center;
                      gap: 20px;
                      margin-top: 20px;
                  }
                  
                  .social-links a {
                      color: white;
                      text-decoration: none;
                      padding: 10px 20px;
                      background: rgba(255,255,255,0.2);
                      border-radius: 25px;
                      transition: background 0.3s ease;
                  }
                  
                  .social-links a:hover {
                      background: rgba(255,255,255,0.3);
                  }
                  
                  @media (max-width: 768px) {
                      .header h1 {
                          font-size: 2rem;
                      }
                      
                      .cards {
                          grid-template-columns: 1fr;
                      }
                      
                      .feature-grid {
                          grid-template-columns: 1fr;
                      }
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <div class="header">
                      <h1>Discord Notify</h1>
                      <p>A Discord API-compliant notification service for Node.js applications</p>
                      <div class="inspiration">
                          <strong>Inspired by Slack Notify</strong> - Designed specifically for Discord's rich webhook capabilities and API features
                      </div>
                  </div>
                  
                  <div class="cards">
                      <a href="API.md" class="card">
                          <h3>📖 API Documentation</h3>
                          <p>Complete API reference with TypeScript interfaces, examples, and usage guides.</p>
                      </a>
                      
                      <a href="api/" class="card">
                          <h3>📋 TypeDoc Reference</h3>
                          <p>Automatically generated TypeDoc documentation with detailed interface information.</p>
                      </a>
                      
                      <a href="https://www.npmjs.com/package/discord-notify" class="card">
                          <h3>📦 NPM Package</h3>
                          <p>Install and use Discord Notify in your Node.js projects with full TypeScript support.</p>
                      </a>
                      
                      <a href="https://github.com/Devlander-Software/discord-notify" class="card">
                          <h3>🐙 GitHub Repository</h3>
                          <p>View source code, contribute, and track issues on our GitHub repository.</p>
                      </a>
                  </div>
                  
                  <div class="features">
                      <h2>🎯 Key Features</h2>
                      <div class="feature-grid">
                          <div class="feature">
                              <h4>🚀 Simple & Easy</h4>
                              <p>Get started in minutes with a familiar API inspired by Slack notification libraries.</p>
                          </div>
                          <div class="feature">
                              <h4>🎨 Rich Embeds</h4>
                              <p>Full Discord embed support with fields, thumbnails, images, and custom colors.</p>
                          </div>
                          <div class="feature">
                              <h4>📎 File Attachments</h4>
                              <p>Direct file uploads without external hosting requirements.</p>
                          </div>
                          <div class="feature">
                              <h4>🧵 Thread Support</h4>
                              <p>Native Discord thread integration for organized conversations.</p>
                          </div>
                          <div class="feature">
                              <h4>📦 TypeScript</h4>
                              <p>Full type definitions and IntelliSense support for better development experience.</p>
                          </div>
                          <div class="feature">
                              <h4>⚡ Zero Dependencies</h4>
                              <p>Lightweight and fast with no external dependencies.</p>
                          </div>
                      </div>
                  </div>
                  
                  <div class="footer">
                      <h3>Join Our Community</h3>
                      <p>Get help, share your projects, and connect with other developers</p>
                      <div class="social-links">
                          <a href="https://bit.ly/devlander-discord-invite">Discord</a>
                          <a href="https://github.com/orgs/Devlander-Software/discussions">GitHub Discussions</a>
                          <a href="https://bit.ly/landonwjohnson-on-twitter">Twitter</a>
                      </div>
                  </div>
              </div>
              
              <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-core.min.js"></script>
              <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/plugins/autoloader/prism-autoloader.min.js"></script>
          </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 